
apiVersion: v1
kind: Service
metadata:
  name: colors-service
  labels:
     app: luis ##Puede ser otra etiqueta
spec:
  type: ClusterIP ##Lo pongo para acostumbrarme
  ports:
  - port: 8080
    protocol: TCP

  selector:
     app: web
--- 
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: colors
  labels:
    app: luis ##Puede ser otra etiqueta
spec:
  selector:  
    matchLabels:
      app: luis
  replicas: 3 
  template:  
    metadata:
      labels:
        app: luis
    spec:
      containers:
      - name: coloread
        image: noloknolo/colors:v1
        ports:   
        - containerPort: 8080
          protocol: TCP
